theforeman/puppet-certs

- README.md
- manifests/init.pp
- manifests/katello.pp
This fixes an issue where for stand alone Capsules that didn't have
access to the server_ca (since it was not deployed) the bootstrap
RPM would fail to be created. Further, this removes the unused
candlepin-local.pem which in reality was just the root CA cert.
> Refs #8756: Deploy the server_ca to the Capsule directories for RHSM.

- lib/puppet/provider/katello_ssl_tool.rb
If two certs have roughly the same name, one can over ride the over
during lookup for existence. For example, katello-foreman-proxy and
katello-foreman-proxy-client would have been resolved to the latter name
and then when the certs are deployed to the certs directory from
the RPMs they would not exist.
> Fixes #9204: Resolve conflict with similar cert names.

- manifests/foreman.pp
Reverts Katello/puppet-certs#50 - this doesn't actually work
```
[root@prometheus katello-installer]# foreman-rake config -k ssl_ca_file -v '/etc/foreman/proxy_ca.pem'      -k ssl_certificate -v '/etc/foreman/client_cert.pem'      -k ssl_priv_key -v '/etc/foreman/client_key.pem'
invalid option: -k
```
@eLobato
> refs #9392 - pass options to foreman-rake config command correctly 

- manifests/katello.pp
- templates/rhsm-katello-reconfigure.erb
This commit adds the katello ca trust pem to the system wide trust store
so that services like docker can now use it
> fixes #8636 - Katello CA cert now trusted system wide

- manifests/ssltools/certutil.pp
Switches to checking for the nssb execute that creates the actual
database instead of just the directory that contains them. This
prevents the following error on EL6:
certutil: function failed: SEC_ERROR_LEGACY_DATABASE: The
certificate/key database is in an unsupported format.
> Fixes #9699: Check for nssdb creation before running certutil.

- manifests/init.pp
- metadata.json
generate_password has a dependency on openssl.
> Fixes #9888 - use random_password over generate_password

- manifests/params.pp
The latest version of the Dispatch Router runs under the qdrouterd
user instead of root as it previously did. This means the certs+keys
all need to be owned by the qdrouterd user instead of qpidd.
> fixes #10350 - switch to qdrouterd user for certs + keys

- templates/rhsm-katello-reconfigure.erb
Improve the check for the docker service in order to restart it if
needed. Also check for systemd based system first and then fall back to
the service based utilities.
> Fixes #9875: Better docker service restart

- manifests/pulp_child.pp
The puppet-pulp 1.0 module removed the consumer_ca_cert parameter
in favor of ca_cert.
> Pulp consumer_ca_cert is now ca_cert

- manifests/pulp_client.pp
Removing the hostname from the client cert and key path as that makes it harder to configure in Katello, and setting the pulp client path in the Settings.
Related to https://github.com/Katello/katello/pull/5750
> Fixes #13635 - set pulp client cert settings

- .fixtures.yml
- manifests/katello.pp
- metadata.json
- spec/classes/certs_katello_spec.rb
Adding Katello Server cert to the machines local ca-trust
> Fixes #13634 - Adding Katello cert to ca-trust

- Gemfile
- manifests/init.pp
- manifests/katello.pp
- spec/classes/certs_katello_spec.rb
- spec/spec_helper.rb
- templates/rhsm-katello-reconfigure.erb
Atomic hosts don't deal with Rpms. This script provides an alternative way to setup the rhsm.conf by including the cert + rpm post script as a separate entity. It also generates a katello-rhsm-atomic-consumer.tar.gz , which has this. So the user is expected download the tar gz , extract, cd into atomic and then run "katello-rhsm-atomic-consumer" script for it to setup rhsm.conf .
> Fixes #10052 - Code to setup rhsm.conf for atomic hosts

- manifests/katello.pp
- templates/rhsm-katello-reconfigure.erb
in a katello_devel install, the variables were not properly looked up
and the ca certificate had not been written to the filesystem yet
> fix bootstrap rpm in katello_devel install

- .fixtures.yml
- manifests/katello.pp
- manifests/rhsm_reconfigure_script.pp
- metadata.json
- templates/rhsm-katello-reconfigure.erb
On Puppet 3.6 the use of File.read in the reconfigure template
causes the certs to be empty given the template is evaluated
at the beginning. This switches to concat to build up the reconfigure
script using the source parameter to read from the cert files.
> Fixes #13925: Use concat to build reconfigure script

- templates/rhsm-katello-reconfigure.erb
Made the code check for "Atomic Host" in /etc/os-release
Works great for redhat 7.2
> Fixes #14223 - Handles atomic machine detection properly

- lib/puppet/provider/certs_bootstrap_rpm/katello_ssl_tool.rb
Old method of sorting used string based comparisons which after 10
release versions fails to sort properly. This moves to a method of
comparing individual releases via integer comparison to derive the
latest boostrap RPM.
> Fixes #12266: Handle last RPM sort for more than 10 bootstrap RPMs

- lib/puppet/provider/certs_bootstrap_rpm/katello_ssl_tool.rb
/Stage[main]/Certs::Katello/Certs_bootstrap_rpm[katello-ca-consumer-centos7-bats.example.com]: no implicit conversion of Hash into String
/usr/share/katello-installer-base/modules/certs/lib/puppet/provider/certs_bootstrap_rpm/katello_ssl_tool.rb:25:in symlink
> Refs #12266 - Fixes no implicit conversion of Hash into String

- lib/puppet/provider/certs_bootstrap_rpm/katello_ssl_tool.rb
undefined method [] for nil:NilClass
/usr/share/katello-installer-base/modules/certs/lib/puppet/provider/certs_bootstrap_rpm/katello_ssl_tool.rb:46:in last_rpm
> Refs #12266 - fixing case where no certs exist

- lib/puppet/provider/katello_ssl_tool.rb
- manifests/candlepin.pp
- manifests/qpid.pp
- manifests/ssltools/certutil.pp
Before this patch, we were relying on the fact that the latest rpms
are always better. However, people often try to rollback to the
previous state of ssl-build and this behavior of the certs script was
causing more troubles than benefits.
After this change, we always use the latest version we have available
in ssl-build by checking if that's what's already installed on the
system or not.
While trying to rollback to some older version of certs, I was hitting
the nssdb errors, as we were not cleaning the certs in there properly.
Therefore I've reused the resource we already had there for certutil,
to clean up certs first.
Steps to test:
1 install katello
2 check the certificiate of web UI
3 `cp ~/ssl-build{,.1}`
4 `foreman-installer --certs-update-all`
5 check the certificiate of web UI
6 …
> Fixes #15538 - make sure the rpms from ssl-build are used

- manifests/ssltools/certutil.pp
When using something short and non-specific like 'ca' to grep the
nssdb output, other words in the nssdb can pass the test. For example,
[root@sat-r220-02 ~]# certutil -L -d /etc/pki/katello/nssdb
Certificate Nickname                               Trust Attributes
SSL,S/MIME,JAR/XPI
amqp-client                                                  ,,
broker                                                       u,u,u
The 'ca' in 'Certificate Nickname' passes the 'grep ca' test.
> Refs #15538: Check for nssdb cert as the beginning of a line

- templates/rhsm-katello-reconfigure.erb
Previously, when generating the client cert RPM, some of these values were
blank due to differences in puppet 3 and 4. This caused clients to not be able
to register.
> Update rhsm config template for puppet 4

- manifests/params.pp
Trying a puppet 3 install, and I get this error:
```
[ERROR 2016-08-04 10:36:46 main]  Could not set 'present' on ensure: No such file or directory - /etc/puppet/ssl/client_cert.pem at 39:/usr/share/katello-installer-base/modules/certs/manifests/puppet.pp
```
Looks like I was wrong (https://github.com/Katello/puppet-certs/pull/95#issuecomment-235951864) about /etc/puppet/ssl existing, just reverting it to the original place we were storing these for puppet 3.
> Use /etc/puppet for client SSL certificates

- manifests/init.pp
- manifests/rhsm_reconfigure_script.pp
Unused since d4a730d70e02a393a9dc265184e3e8f87a7b86e8 and causes issues
with strict variables.
> Remove unused password_file_dir parameter

- metadata.json
There are other modules that require `foreman-theforeman > 6.0.0`,
which would break when this module was imported into librarian.
> Bump foreman dependency

- manifests/katello.pp
In some custom setups (like Red Hat's HA ref arch), users may change the node_fqdn to match something like a load balancer's virtual hostname.  This ensures we use the node_fqdn variable if they did that, but otherwise node_fqdn default value is fqdn anyway.
> fixes #16945 - use node_fqdn for consumer cert RPM generation

- lib/puppet/provider/cert/katello_ssl_tool.rb
- lib/puppet/type/certs_common.rb
- manifests/candlepin.pp
- manifests/qpid.pp
This will require the user to do a `--certs-update-all` for the next upgrade, so qpid gets the new cert with the additional CN.
> refs #11737 - support cnames and add localhost cname to qpid certs

- manifests/tar_extract.pp
certs::tar_extract always use -xzf option even though the file was not compressed.
When I run the command below, the foreman-installer fails due to this problem.
```
foreman-installer --scenario capsule --capsule-certs-tar /root/katello-httpd-ssl-archive-capsule01.example.net-1.0-10.tar --certs-update-all
```
please change the option.
> Changed tar option to determine the file is compressed or not

- manifests/puppet.pp
The UID is not using the assigned one:
https://tickets.puppetlabs.com/browse/SERVER-1381, so we can't do the 52
trick.  We need to require the puppet server install class to ensure the
package is installed first.
> fixes #17863 - use puppet user not uid

- manifests/apache.pp
- manifests/candlepin.pp
- manifests/foreman.pp
- manifests/foreman_proxy.pp
- manifests/foreman_proxy_content.pp
- manifests/init.pp
- manifests/params.pp
- manifests/pulp_client.pp
- manifests/puppet.pp
- manifests/qpid.pp
- manifests/qpid_client.pp
- manifests/qpid_router.pp
This PR does not completely fix http://projects.theforeman.org/issues/15931 aka https://bugzilla.redhat.com/show_bug.cgi?id=1160344, but it at least allows to actually generate certificates with multiple names in them which would have prevented the mentioned issue.
The `cert` resource already knows how to handle `katello-ssl-tool`s `--set-cname`, so we just have to pass the right value to it. This is done by creating a default `[]` cname parameter and passing this along to all `cert` invocations. Kafo then can override the value via the command line.
> refs #15931 - allow passing the cname parameter when generating certs

- manifests/foreman_proxy_content.pp
Values inside `certs` aren't available when `foreman-proxy-certs-generate` is run:
```
[root@certs certs]# foreman-proxy-certs-generate --certs-tar /root/foo.tar.gz --foreman-proxy-fqdn foo.example.com
Parameter foreman-proxy-cname invalid: nil is not a valid array
```
so we need to get the defaults from the `params`, instead.  I can't think of a better solution.
In order to generate proxy certs with cnames the command would be:
```
foreman-proxy-certs-generate --certs-tar /root/foo.tar.gz --foreman-proxy-fqdn foo.example.com --foreman-proxy-cname foo-lb.example.com`
```
> Only reference ::certs::params values in foreman_proxy_content

- lib/puppet/provider/katello_ssl_tool.rb
- lib/puppet/provider/privkey/katello_ssl_tool.rb
- lib/puppet/type/certs_common.rb
This is currently untested using puppet apply.
@ehelms, @ekohl: Could you take a look please?
> fixes #17572 - module works with master compile

- manifests/foreman_proxy.pp
The file is world readable, setting the owner to user
`foreman` causes errors because a user named `foreman` does not exist
on a system with just foreman proxy installed.
Removing the owner causes the file to be owned by root which is fine as
it is world readable.
> foreman_proxy does not need foreman user

- manifests/apache.pp
- manifests/candlepin.pp
- manifests/config.pp
- manifests/foreman.pp
- manifests/foreman_proxy.pp
- manifests/foreman_proxy_content.pp
- manifests/init.pp
- manifests/install.pp
- manifests/katello.pp
- manifests/pulp_client.pp
- manifests/puppet.pp
- manifests/qpid.pp
- manifests/qpid_client.pp
- manifests/qpid_router.pp
- manifests/tar_create.pp
* Use the absolute $::certs::
* Use local variables where possible
* Correct indenting
> Make variable usage and indenting consistent

- .fixtures.yml
- metadata.json
* puppet-extlib version 1.x has no incompatiblities compared to 0.x.
* evenup-trusted_ca was transfered to jlambert121-trusted_ca.
> Allow newer versions of dependencies

- manifests/qpid.pp
`qpid` has a dependency on `apache` although the former works perfectly fine without the latter.
> qpid does not need apache

- .fixtures.yml
- manifests/candlepin.pp
- manifests/foreman_proxy.pp
- manifests/qpid.pp
This commit removes dependencies to external services.
They should be defined in a profile module, something like this:
```puppet
Certs::Ssltools::Certutil <| |> ~> Service['qpidd']
Class['certs::apache'] -> Service['httpd']
Class['certs::candlepin'] ~> Service['tomcat']
Class['certs::qpid'] ~> Service['qpidd']
Class['certs::foreman_proxy'] ~> Service['foreman_proxy']
Class['puppet::server::install'] -> Class['certs::puppet']
```
> remove dependencies to external modules

- manifests/candlepin.pp
- manifests/qpid.pp
- manifests/ssltools/certutil.pp
- manifests/ssltools/nssdb.pp
Both `qpidd` and `candlepin` need the `nssdb` present. This commit extracts the code to a common class.
> extract nssdb creation into separate class

- manifests/qpid.pp
In bf4d1d9b63baa1cbaa573ae9e26e53d78ead46c2 the dependency on Apache was
removed but accidentally reintroduced in
0758e06b1d977741b5e6bc4167629eb9eafd36d3.
> Fix qpid dependency on apache

- metadata.json
This was added for the random_password function but that has been moved
to puppet-extlib.
Or am I missing something?
> Remove a dependency on theforeman-foreman

- manifests/candlepin.pp
This should go into the katello module. I haven't written the code for the module, yet. Currently, this is just a reminder.
> move qpidd reload to katello module

- manifests/apache.pp
- manifests/candlepin.pp
- manifests/foreman.pp
- manifests/foreman_proxy.pp
- manifests/katello.pp
- manifests/pulp_client.pp
- manifests/puppet.pp
- manifests/qpid.pp
- manifests/qpid_client.pp
- manifests/qpid_router.pp
- spec/classes/certs_apache_spec.rb
- spec/classes/certs_candlepin_spec.rb
- spec/classes/certs_foreman_proxy_content_spec.rb
- spec/classes/certs_foreman_proxy_spec.rb
- spec/classes/certs_pulp_client_spec.rb
- spec/classes/certs_puppet_spec.rb
- spec/classes/certs_qpid_router_spec.rb
- spec/classes/certs_qpid_spec.rb
As promised, this is the first PR to clean up the certs module. It includes some very basic test coverage. I want to extend it when working on the following list:
More issues we should fix:
* Client certs should not have a cname
* This module should not have any dependencies to tomcat, apache or whatever. The resource ordering should be done in the katello module.
* The classes that actually generate certificates should be defined types to allow reuse.
> classes inherit from init

- manifests/apache.pp
Foreman launches websockify process that needs read access to
this key.
> fixes #19259 - apache key should be mode 0440

- templates/rhsm-katello-reconfigure.erb
Restarting docker service will stop all the running containers, so instead of restart we should reload the service which will not affect any running container.
> Fixes #19271 - reload docker instead of restart

- manifests/candlepin.pp
otherwise `Exec[import client certificate into Candlepin keystore]` has no relationship with `File[/etc/pki/katello/keystore_password-file]` and Puppet might execute them in any order, but the Exec needs the File.
> Fixes #19734 - enforce proper exection order for Candlepin

- manifests/foreman_proxy_content.pp
- types/relativeunixpath.pp
No puppetlabs-stdlib data type exists for any sort of relative url, so we have to roll our own. This could _probably_ go into a more generic module, but I figured for simplicity of not having 3+ chained PRs...
http://projects.theforeman.org/issues/19578
> #19578 - Switch to custom datatype for path validation

- manifests/katello.pp
- manifests/qpid.pp
- spec/classes/certs_katello_spec.rb
This should effectively be no change.
> Simplify variable access

- .sync.yml
- .travis.yml
- spec/acceptance/certs_spec.rb
Based on https://github.com/Katello/puppet-certs/pull/160 with some slight changes. I'll expand this later to more classes so we have a baseline of working manifests before I attempt to refactor.
> Add acceptance tests

- manifests/apache.pp
- spec/acceptance/apache_spec.rb
This reduces coupling to other modules and will allow much easier testing while increasing security.
Apache uses the root user to read certificates and private keys so we can tighten the permissions to ```root:root 0640```.
In puppet-katello we already subscribe to it [here](https://github.com/Katello/puppet-katello/blob/451530b0b161d41ab09f10333f3e849c82cda70d/manifests/application.pp#L52) and that is equal.
In puppet-foreman_proxy_content we subscribe to it [here](https://github.com/Katello/puppet-foreman_proxy_content/blob/c0a476813ecda9cdc0af324faa3c8be05c886364/manifests/init.pp#L116-L125) but I'm not 100% sure yet if this is equal. Ordering should be correct but if Apache is actually reloaded is not guaranteed. https://github.com/Katello/puppet-foreman_proxy_content/pull/136 will …
> Drop apache username/password

- manifests/ssltools/nssdb.pp
- spec/acceptance/candlepin_spec.rb
This is how an acceptance test for candlepin could look like. Currently it doesn't pass yet and we should move more code into common areas to manage the repositories.
This includes https://github.com/Katello/puppet-certs/pull/144, builds on https://github.com/Katello/foreman-installer-modulesync/pull/20 and relates to https://github.com/Katello/puppet-pulp/issues/164.
> Add an acceptance test for candlepin

- metadata.json
We use Stdlib::Absolutepath which was introduced in 4.13.0.
> Correct stdlib dependency

- manifests/candlepin.pp
- manifests/params.pp
- spec/classes/certs_candlepin_spec.rb
https://github.com/Katello/puppet-katello/commit/4e1371e8c93d75465b1f5b5f8fd025b90c8b9424 started to manage think symlink as well. That means we can stop managing it here.
> Stop managing tomcat keystore symlink

- .fixtures.yml
- manifests/puppet.pp
- spec/classes/certs_foreman_proxy_content_spec.rb
- spec/classes/certs_puppet_spec.rb
https://github.com/theforeman/puppet-puppet/commit/2fb8ad506566092d146492f49e7892ca0fb93b64 ensures the puppet user is always managed. This means the file resource will autorequire the user causing the chaining to work.
> Use implicit dependency chaining on puppet

- manifests/rhsm_reconfigure_script.pp
Not sure if you want this, but whenever this option is not set for a shell script, i loose days searching for the line where something failed.
> Add "set -e" to consumer script

- templates/rhsm-katello-reconfigure.erb
```
Running Transaction                             
Installing : katello-ca-consumer-centos7-dev2.strangeways.example.com-1.0-1.noarch                                                                                                           1/1 
sed: can't read /etc/os-release: No such file or directory                                       
warning: %post(katello-ca-consumer-centos7-dev2.strangeways.example.com-1.0-1.noarch) scriptlet failed, exit status 2                                                                              
Non-fatal POSTIN scriptlet failure in rpm package katello-ca-consumer-centos7-dev2.strangeways.example.com-1.0-1.noarch                                                                              Verifying  : …
```
> Fix debian OS determination

- templates/rhsm-katello-reconfigure.erb
The adding of a subscription-manager fact is failing on
stock SLES12 installs as 'hostname -f' doesn't work "out of
the box":
`hostname: Name or service not known`
This is due to /etc/hosts not having the FQDN associated with
127.0.0.1
Its an easy fix, but for automated provisioning/scripting we
want to be sure the bootstrap rpm script will run without
issues.
The subscription manager hostname-override fact isn't
needed for subscription manager versions past 1.18.1-1,
so we can skip this block of code for later versions.
This commit checks the subscription manager version before
adding the hostname-override fact. This is something we
should do anyways and it avoids the error for SLES.
SLES will use subscription-manager-1.20.5-7.1.x86_64 or
later, so this block of code isn't even needed.
> Fixes #22884 - Check RHSM version for hostname-override

- .fixtures.yml
- lib/puppet/parser/functions/validate_file_exists.rb
- manifests/foreman_proxy_content.pp
- spec/classes/certs_foreman_proxy_content_spec.rb
- spec/functions/validate_file_exists_spec.rb
there wasn't a dependency on puppet-common in the manifest. that seems unexpected!
> Remove dependency on puppet-common

- manifests/candlepin.pp
- spec/acceptance/candlepin_spec.rb
I don't see any reasoning for this code being there. Basically, it adds candlepin's `java-client` cert (the cert candlepin uses to connect to qpidd) to the qpidd truststore.
Candlepin doesn't need this to boot up. And it doesn't need this to connect to qpidd. We don't do anything similar elsewhere. I mean, isn't the idea of a PKI to not whitelist individual certificates but trust the CA?
Anyways, this removes another dependency. Goes along with https://github.com/Katello/puppet-katello/pull/215 to remove the qpidd dependency.
> candlepin: remove nssdb dependency

- manifests/init.pp
Hi,
This is one of a series of patches to address typos in `katello-installer --help` [#15963](http://projects.theforeman.org/issues/15963)
This diff addresses the `--certs-deploy`, `--certs-regenerate`, and `--certs-regenerate-ca` parameters' descriptions, changing them from:
~~~
--certs-deploy                Deploy the certs on the configured system. False means
we want apply it on a different system (current: true)
...
--certs-regenerate            Force regeneration of the certificates (excluding
ca certificates) (current: false)
...
--certs-regenerate-ca         Force regeneration of the ca certificate (current: false)
~~~
To:
~~~
--certs-deploy                Deploy the certs on the configured system. False means
we want to apply it to a different system (current: true)
... …
> Refs #15963 - katello-installer --help typos

- manifests/apache.pp
- spec/classes/certs_apache_spec.rb
For Katello, we override the certs ownership so Foreman can read it.
This is required for WebVNC: the foreman user launches websockify
using the certificate.
Partially reverts https://github.com/theforeman/puppet-certs/pull/168
> fixes #24210 - certs group must be overridable

- .fixtures.yml
- metadata.json
This fork is maintained and compatible with the latest Puppet and stdlib
versions.
Also cleans up the fixtures to use current URLs.
> Switch to puppet-trusted_ca & allow puppet-extlib 3.0

- templates/rhsm-katello-reconfigure.erb
Correctly detect debian derivatives like Ubuntu, Linux Mint, etc.
> Add support for debian derivatives

- templates/rhsm-katello-reconfigure.erb
&> is allowd but 2&>1 is not allowed.
> Fix wrong redirect notation

- templates/rhsm-katello-reconfigure.erb
rhsm-katello-reconfigure.erb template had incorrect sed syntax due to which katello-ca-consumer rpm was creating with incorrect /usr/bin/katello-rhsm-consumer.
> Fixes #25512 fixes incorrect editing of rhsm.conf

- manifests/candlepin.pp
- manifests/params.pp
- manifests/qpid.pp
Both in candlepin.pp and in params.pp they are unused so we can remove them. For qpid it shouldn't be a class parameter because one could override it in the nssdb class and things would break.
Technically we should remove it from init.pp too and only define it in nssdb.pp as a class parameter default, but puppet-katello uses it on the main class so we keep it in for now.
> Clean up $nss_db_dir handling

- manifests/init.pp
- manifests/params.pp
This moves the parameter from puppet-katello and puppet-foreman_proxy_content into puppet-certs. This will need an installer migration as well.
> Refs #24947 - Allow extract tar files at the top level

- manifests/candlepin.pp
- manifests/keypair.pp
- spec/acceptance/candlepin_spec.rb
Need to test this still but I want to see if a test fails so I can fix it or write a new one.
> Candlepin CA should be owned by tomcat user

- templates/rhsm-katello-reconfigure.erb
When a bash script is executed with `set -e`, it will fail immediately
when a subcommand fails. From bash(1):
-e    Exit immediately if a pipeline (which may consist of a single
simple command), a list, or a compound command (see SHELL
GRAMMAR above), exits with a non-zero status.
Running scripts with `-e` is generally a good idea, but this means that
we can't allow subcommands to fail anymore and then handle the error
case based on `$?`.
This commit replaces the two places where we relied on the value of `$?`
with code that will _never_ fail and at least return a dummy value which
we then can act on.
> Fixes #25739 - don't allow statements to fail in an set -e script

- manifests/foreman_proxy_content.pp
- manifests/init.pp
- metadata.json
This also moves back to the global facts as parameter defaults because it looks like kafo has issues with extracting the proper default.
> Use FQDNs data types where appropriate

- templates/rhsm-katello-reconfigure.erb
Subscription manager adds the ability to turn on and off package  uploads  on a DNF transaction.
This is accomplished by setting the "package_profile_on_trans" flag in /etc/rhsm/rhsm.conf
This commit accomplishes that.
> Fixes #25873 - Set rhsm package upload options

- lib/puppet/provider/katello_ssl_tool.rb
- lib/puppet/type/certs_common.rb
- manifests/foreman_proxy.pp
Apaches's SSLProxyMachineCertificateFile is not able to find a key
wrapped in `-----BEGIN PRIVATE KEY-----`, which is the format that is
generated when running the server in FIPS mode. It seems that just making
sure the RSA word is there make Apache happy to find the key.
I've added `force_rsa` option for the cert files resources to enforce the
RSA word to be there when wrapping the private key + used that to
generate the client bundle for SSL proxy to use it.
> Fixes #26088 - ensure RSA word for SSLProxyMachineCertificateFile

- lib/puppet_x/certs/common.rb
- spec/types/ca_spec.rb
- spec/types/cert_spec.rb
- spec/types/key_bundle_spec.rb
- spec/types/privkey_spec.rb
- spec/types/pubkey_spec.rb
Before the patch only the path itself was autorequired but this copies the autorequire from Puppet's file which autorequires all parts of the path to the root. This ensures that the parent directory exists before the provider attempts to write the file and fixes errors like:
[ERROR 2019-09-14T04:58:09 main] Could not set 'present' on ensure: No such file or directory @ rb_sysopen - /etc/pki/katello/private/katello-apache.key (file: /usr/share/foreman-installer/modules/certs/manifests/keypair.pp, line: 18)
[ WARN 2019-09-14T04:58:25 main] /Stage[main]/Certs::Config/File[/etc/pki/katello/private]/ensure: created
Also adds minimal spec tests for ca and cert types.
> Fixes #27857 - autorequire parent paths in types

- manifests/foreman_proxy_content.pp
- manifests/foreman_proxy_content/params.pp
- spec/classes/certs_foreman_proxy_content_spec.rb
* Move `$parent_fqdn` to Advanced Parameters since users generally don't touch this
* Implement stricter data types
* Use modern facts
* Work around a kafo_parsers/puppet-strings limitation by using class inheritance
> Fixes #27847 - Refactor foreman_proxy_content class

- manifests/foreman_proxy_content.pp
3beda1df35481210b581f9beeb63d1dcafd2aca0 intended to load the variable from params and even added it to params.pp, but missed using that variable.
> Refs #27847 - Load CNAME default from params

- manifests/foreman_proxy_content.pp
- manifests/foreman_proxy_content/params.pp
In foreman-installer we test the command inside bundler. There is only a facter 2 gem which doesn't have the modern facts. That means `$facts['networking']` is `undef` and breaks, even though this won't be a problem in production. In many places we still use legacy facts so this reverts back to legacy facts.
> Refs #27847 - Use legacy facts

- manifests/apache.pp
This allows usnig `$certs::apache::apache_ca_cert` in other manifests that just does the right thing, rather than having to know it other modules.
> Set a variable that defines the Apache CA

- metadata.json
Recent versions of puppet-blacksmith started to require this. The forge username is also lowercase so it does match now.
> Correct author case to name in metadata

- manifests/qpid.pp
This variable becomes an API which users of this class can reuse rather than hardcoding it.
> Expose the qpid nss cert name as a variable

- manifests/qpid_client.pp
This should solve https://github.com/theforeman/puppet-pulpcore/issues/22 by setting the group owner and permissions of `/etc/pki/pulp` to be compatible with pulp3
> /etc/pki/pulp perms and group owner

- manifests/init.pp
- manifests/params.pp
d4a730d70e02a393a9dc265184e3e8f87a7b86e8 stopped using this parameter and there's nothing using it anymore.
> Remove unused $regenerate_ca parameter

- metadata.json
Due to ec654e3f6ea563fb9bfb7de48fc3c58ccae10a8d and 23faa5462d0e8a1ddafb86304e4749c1ab6a5f7a which are both breaking.
> Bump major version to 7.0.0

- .sync.yml
- spec/acceptance/apache_spec.rb
- spec/acceptance/candlepin_spec.rb
- spec/acceptance/certs_spec.rb
- spec/spec_helper_acceptance.rb
This also replaces latest katello with foreman nightly. Katello latest points to 3.8 where in later releases katello-certs-tools was moved to the Foreman repository. EPEL was actually unused.
> Move repository setup to the spec helper & drop EPEL

- templates/rhsm-katello-reconfigure.erb
@jlsherrill @parthaa Could y'all confirm that these can safely be removed for Katello 4.0 and point to anything else that might could be removed? I left in the EL5 host override fact for now given EL5 EOLs in November of this year which more closely aligns with 4.1.
> Fixes #30312: Drop docker, atomic and goferd support from consumer RPM

- manifests/params.pp
5f2f0557606241a2bb08e5f798a3a231b72cbf38 removed the use of these variables but didn't remove the definitions.
> Remove unused $katello_* params

- manifests/foreman_proxy.pp
- spec/acceptance/foreman_proxy_spec.rb
This changes the file owner to be root. This prevents the service for being able to modify the files. Because it still needs to read the files, the group is changed to foreman-proxy.
The public key permissions are also modified to 640. While 644 would work, it's common in PCI compliant setups to restrict this. Only foreman-proxy should read these files so it should have no impact. However, it may be used by humans who debug a service. They may notice a difference.
I'm not entirely sure the public key needs to be limited. I'd like to find a citation of the PCI requirements that dictates this.
> Change foreman-proxy file ownership to 440

- manifests/init.pp
- manifests/params.pp
Fixes the following error during validation:
Parameter certs-cname invalid: Elements of the array are invalid: [] must match one of
(?-mix:\A(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])\z
> Move cname default back to params.pp due to Kafo improperly handling validation

- manifests/foreman_proxy_content.pp
- manifests/foreman_proxy_content/params.pp
This reverts commit 920130e781c2e31c6b4598a7df1b911443bd6f50. Similar to 6be51bcdbc571f6c926624be24e585edc9593e89 this causes problems. params.pp already states exactly why the workaround is there, but this was not read and wasn't seen in review either.
> Revert "Convert foreman_proxy_content.pp parameters to static defaults"

- lib/puppet/provider/truststore_certificate/keytool.rb
- lib/puppet/type/truststore_certificate.rb
- manifests/candlepin.pp
- spec/acceptance/candlepin_spec.rb
This combines https://github.com/theforeman/puppet-certs/pull/312 with the updated testing from https://github.com/theforeman/puppet-certs/pull/311/files#diff-5afea89f9f4123c60bf87969c1a02b0d75c0687a14758480314204b44ca679c1R189 to get to a PR that resolves this issue and we can pull in. There have been additional reports of users hitting this issue.
> Fixes #31574: Ensure truststore certificates get updated when they change

- lib/puppet/provider/truststore_certificate/keytool.rb
- manifests/candlepin.pp
- spec/acceptance/candlepin_spec.rb
I'm very confused. Between the last time https://github.com/theforeman/puppet-certs/pull/320 ran which as March 17th, something has changed that causes the idempotency of this new type and provider to break.  This only seems to occur on EL7. I have added two debug statements here that highlight so far what I know which is that the `is` value is nil when doing the `insync?` check.
> Refs #31574: Compare SHA256 fingerprints when checking truststore

- metadata.json
Given we are adding enhancements and will have modules that depend on and use those enhancements this will allow updating those module metadata's to the right version.
> Bump master to 12.1.0

- lib/puppet/provider/nssdb_certificate/certutil.rb
- lib/puppet/type/nssdb_certificate.rb
- manifests/qpid.pp
- spec/acceptance/qpid_spec.rb
- spec/classes/certs_qpid_spec.rb
This adds a type for managing NSS database certificates (and private keys)
within an NSS database. This new type reduces the number of intermediary
entities that have to be created, for example the pkcs12 export, and
reduces the overall Puppet code required. This type aims to provide
a clean interface to managing NSS database certificates and ensure
that the NSS database is in sync with the certificates being managed.
Requires: https://github.com/theforeman/puppet-certs/pull/326
> Fixes #32506: Add an nssdb_certificate type and provider 

- lib/puppet/provider/keystore/keytool.rb
- lib/puppet/type/keystore.rb
- manifests/candlepin.pp
This allows creating and managing a PKCS12 based keystore that
is initially empty. This allows managing the permissions and ownership
of the keystore separately from any certificates within it.
This is an alternative to what was discussed here -- https://github.com/theforeman/puppet-certs/pull/329#discussion_r629315815
The follow up would be then to introduce a type `keystore_certificate` that would roughly look like:
```
keystore_certificate { "${keystore}:tomcat":
ensure          => 'present',
certificate     => $tomcat_cert,
private_key  => $tomcat_key,
ca_file           => $ca_cert,
password_file => $keystore_password_path,
}
```
Where keystore_certificate would have an autorequires on `Keystore[$keystore]` effectively. While I like the discussed all in one declaration:
```
keystore { …
```
> Fixes #32506: Add keystore puppet provider type

- lib/puppet/type/keystore.rb
In 47db06c5fd01fba4e06af5325470c8c146074bba a new keystore provider was added. This modifies metaparams in place which can have side effects. This patch changes it to not need it.
Fixes: 47db06c5fd01fba4e06af5325470c8c146074bba
> Refs #32506 - Avoid in place modification of array

- lib/puppet/provider/keystore/keytool.rb
- lib/puppet/provider/truststore/keytool.rb
- lib/puppet/type/truststore.rb
- lib/puppet_x/certs/provider/keystore.rb
- manifests/candlepin.pp
- spec/acceptance/truststore_spec.rb
Builds on #334 re-factoring what is present there into a common module.
I did not want to create one giant PR with all of these types but rather a set of progressive PRs that build one on each other to make it easier to review, discuss and ultimately to merge in smaller logical pieces.
> Fixes #32637: Add truststore type and provider 

- lib/puppet/provider/ca/katello_ssl_tool.rb
- lib/puppet/provider/cert/katello_ssl_tool.rb
- lib/puppet_x/certs/common.rb
- manifests/apache.pp
- manifests/ca.pp
- manifests/candlepin.pp
- manifests/foreman.pp
- manifests/foreman_proxy.pp
- manifests/pulp_client.pp
- manifests/puppet.pp
- manifests/qpid.pp
- manifests/qpid_router/client.pp
- manifests/qpid_router/server.pp
The build directory for certificates is declared as a parameter
but has no direct link to what the underlying tool would use
as the build directory. This change links the two up so that
there is no discrepancy and enables relying on the build directory
and paths within it.
> Declare the build directory for all certificate creation

- .fixtures.yml
- metadata.json
953261ffd2eb52b7176ab365fb0c4e9245435d99 removed the last use of trusted_ca so this module no longer depends on it.
Marking as an enhancement since this should result in a minor version bump. It was noted that theforeman/foreman_proxy_content didn't add the dependency explicitly. We do bump patch versions in stable releases and that can break.
Fixes: 953261ffd2eb52b7176ab365fb0c4e9245435d99
> Remove dependency on trusted_ca

- spec/acceptance/qpid_spec.rb
- spec/support/acceptance/matchers/match_without_whitespace.rb
This matcher can be used when command output is broken up by
whitespace characters.
> Add match_without_whitespace custom matcher

- manifests/tar_create.pp
- spec/acceptance/certs_tar_extract_spec.rb
Requires: https://github.com/theforeman/puppet-certs/pull/351
Adding a bit more than what is in the commit message. This is working towards an approach that we deploy certificates from the build directory to their managed locations and eventually drop the use of RPMs. This will cut down on the amount of locations certificates exist, the amount of processing by the puppet module and open this up for use on non-RPM systems.
In order to do this I am trying an approach of re-factoring underneath that does additive changes that allow the end state to remain unchanged while dismantling all of the RPM mechanisms. So in this case, include the certificates in the tarball, this will allow them to exist in `/root/ssl-build`. From there, we can begin to make changes such as in …
> Include certs directory tarball

- spec/acceptance/foreman_spec.rb
This was a minor oversight in 0a362f38a95b701e9dbd3b528a462c6212d5751a
> Test that foreman client_cert.pem has keylength >= 4096

- lib/puppet/provider/katello_ssl_tool.rb
- lib/puppet/provider/key_bundle/katello_ssl_tool.rb
- lib/puppet_x/certs/common.rb
- manifests/keypair.pp
- spec/defines/keypair_spec.rb
This includes https://github.com/theforeman/puppet-certs/pull/313/commits/862fc57d27aece10ab182236f5bd2fbb91390217 with a small fix to allow tests to pass (thanks @ekohl !).
> Support ensuring certs::keypair cert and key can be absent

- manifests/foreman.pp
- spec/acceptance/foreman_spec.rb
This manages the ssl_ca_file in certs::foreman ensuring the right
owner and group are set and allowing users of this class to customize
it if needed.
@ekohl Needed to implement https://github.com/ekohl/puppet-katello_devel/commit/8e2f945cd4e70d8e39737ad5a90c3e431442f22b otherwise the `proxy_ca.pem` file would end up owned by root:root.
> Manage the certs::foreman ssl_ca_file

- manifests/qpid_router/client.pp
Fixes:
```
```
When configuring the client certificates, we configure a string for the "hostname" (CN) as part of the SASL configuration to identify the user.
> Allow passing string for hostname to certs::qpid_router::client

- manifests/candlepin.pp
Candlepin supports configuring a CA key password, so deploying the
CA key to Candlepin unprotected only complicates deployment by having
to run an intermediary step to unprotect it. Let the key be deployed
as is and configure Candlepin appropriately.
> Keep Candlepin CA key password protected

- spec/acceptance/certs_tar_extract_spec.rb
- spec/acceptance/foreman_proxy_content_spec.rb
- spec/support/acceptance/tar.rb
Aims to allow testing for regressions when certificates are added
or removed when aiming to support Katello N-1 support. Additionally
aims to detect if new items are added that should be checked for.
> Add test to check tar archive contents

- lib/puppet/type/cert_key_bundle.rb
- manifests/foreman_proxy.pp
- spec/acceptance/foreman_proxy_spec.rb
Adds a new type to create a bundle of a certificate and private key
that relies on certificate and private key paths being supplied. The
current key_bundle type is tied closely to the underlying katello-certs-tools
based types. This new type is more widely usable across use cases and
combines the ability to manage file properties.
> New cert key bundle type

- manifests/apache.pp
In 8c5404ff76aca156be16f81b1f21b630a067b2c2 this was removed, but it was considered a public API. It makes it easy for consumers to know what the actual CA is.
Fixes: 8c5404ff76aca156be16f81b1f21b630a067b2c2
> Reintroduce $apache_ca_cert

- lib/puppet/provider/private_key/openssl.rb
- lib/puppet/type/private_key.rb
- manifests/candlepin.pp
- manifests/keypair.pp
- spec/acceptance/candlepin_spec.rb
- spec/defines/keypair_spec.rb
Introduces a new type and provider for managing a private key file.
Has the ability to decrypt the private key file when deploying
which is needed for Candlepin deployments.
> Fixes #34189: Unencrypt CA key when deploying for Candlepin

- lib/puppet/provider/keystore_certificate/openssl.rb
- lib/puppet/provider/truststore_certificate/keytool.rb
- lib/puppet_x/certs/provider/keystore.rb
Starting with EL 8, the Java stack has FIPS support built in. This
causes the keytool utility to break on FIPS enabled machines. To solve this,
and achieve EL7-like comptability for FIPS, FIPS is disabled during the keytool
runtime via -Dcom.redhat.fips=false for each invoke of keytool.
> Fixes #34598: Disable fips for keytool 

- manifests/ca.pp
There is nothing secret in that file, and this allows non-root users to
use hammer and friends to check the HTTPS cert of the server.
Fixes: 028f93af283b718752e6263b2732c8c0ce308caf
> Fixes #35335 - allow everyone to read the Katello CA certificate

- lib/puppet/provider/keystore/keytool.rb
- lib/puppet/provider/truststore/keytool.rb
- lib/puppet/type/cert_key_bundle.rb
- lib/puppet/type/keystore.rb
- lib/puppet/type/nssdb.rb
- lib/puppet/type/private_key.rb
- lib/puppet/type/truststore.rb
- lib/puppet_x/certs/provider/keystore.rb
Fixes #388
This also fixes errors I was seeing with `puppet generate types` during deploy.
> Fix bad requires and old Puppet_X notation

- manifests/ca.pp
- manifests/init.pp
- spec/acceptance/certs_spec.rb
As the pki_dir is intended for deployment rather than generation, and the CA password file is needed primarily for certificate generation it should reside in the build directory.
> Deploy the CA password file to ssl build directory

- lib/puppet_x/certs/common.rb
Some fields are always required and things break if they are not set. It's also possible to automatically require the password files which gives a better guarantee that things are executed in the correct order.
> Set required params and autorequire

- lib/puppet_x/certs/provider/keystore.rb
- spec/acceptance/keystore_spec.rb
Opening the store when checking if it exists will raise an exception if the password is incorrect. This takes an approach of catching all exceptions and treating them all the same.
Right now it doesn't work yet and I'm getting integrity errors so I suspect it may not recreate the file. Need to do some further digging.
> Support changing passwords on keystores & truststores

- metadata.json
There have been breaking changes and this reflects that. It allows creating a stable branch without immediately releasing all changes.
> Bump major version to reflect next release

- lib/puppet_x/certs/provider/keystore.rb
- spec/acceptance/truststore_spec.rb
When using keytool on a truststore the error is different than on a keystore.
Fixes: 6fea0bbb4143ca439cff01bf9f0e54cf88140d10 ("Support changing passwords on keystores & truststores")
> Handle more unknown password errors

- lib/puppet/provider/ca/katello_ssl_tool.rb
- lib/puppet/provider/katello_ssl_tool.rb
- lib/puppet/provider/key_bundle/katello_ssl_tool.rb
- lib/puppet/provider/privkey/katello_ssl_tool.rb
- spec/classes/certs_qpid_router_client_spec.rb
- spec/classes/certs_qpid_router_server_spec.rb
https://github.com/theforeman/puppet-certs/pull/412 was merged with failing CI. I used auto-merge, but there is a required check. That did not pass and still it was merged. This PR fixes the failures and makes Puppet 8 work. Technically they're really Ruby 3 fixes, but that's what Puppet 8 ships.
> Fix some RuboCop flagged issues for Puppet 8 support

- manifests/tar_create.pp
This way users can pass .tar.xz to get XZ compression too. One side effect is that by default we won't compress anymore since the file extension is .tar. On the other hand, it's less confusing for users that you have a .tar extension which should be .tar.gz.
This was noted in https://bugzilla.redhat.com/show_bug.cgi?id=1874045#c5. Right now this is a draft because I think we first need to have a discussion on whether this is correct. Note `certs::tar_extract` already has `-a` so it should pick it up already.
> Use automatic compression based on file path for tar

- manifests/tar_create.pp
- spec/acceptance/foreman_proxy_content_spec.rb
These were kept in for N-1 support when we first switched away from using RPMs for deployment. Enough release have passed that we can drop this.
> Drop RPMs from being included in tarball

- manifests/apache.pp
- manifests/ca.pp
- manifests/foreman_proxy.pp
- spec/acceptance/certs_spec.rb
This simplifies the code required to make the server CA certificate which is either just a copy of the default CA or the supplied custom CA certificate from a user.
The current implementation requires the server CA certificate in the `build_dir` due to how we generate the tarball for Capsules.
Stay tuned for further enhancements, for now this is a small step simplification.
> Copy the server CA certificate with file resource

- spec/acceptance/apache_spec.rb
- spec/acceptance/candlepin_spec.rb
- spec/acceptance/certs_spec.rb
- spec/acceptance/certs_tar_extract_spec.rb
- spec/acceptance/foreman_proxy_spec.rb
- spec/acceptance/foreman_spec.rb
- spec/acceptance/puppet_spec.rb
The openssl output is not always guaranteed to be the same so this nromalizes the whitespace.
> Fix tests on EL9

- lib/puppet_x/certs/provider/keystore.rb
In a FIPS-enabled environment, calling `keytool -list` with a wrong password doesn't yield an error, unless we also pass `fips=false` like we do when creating the keystore:
Keystore type: PKCS11
Keystore provider: SunPKCS11-NSS-FIPS
Your keystore contains 0 entries
Passing `fips=false` makes it correctly raise the expected exception:
keytool error: java.io.IOException: keystore password was incorrect
Fixes: 6fea0bbb4143ca439cff01bf9f0e54cf88140d10
> Fixes #37384 - properly pass fips=false when checking keystore

- lib/puppet/provider/ca/katello_ssl_tool.rb
- lib/puppet/provider/cert/katello_ssl_tool.rb
- lib/puppet/provider/katello_ssl_tool.rb
- lib/puppet_x/certs/common.rb
- manifests/apache.pp
- manifests/ca.pp
- manifests/candlepin.pp
- manifests/foreman.pp
- manifests/foreman_proxy.pp
- manifests/init.pp
- manifests/puppet.pp
This includes commits that are in existing PRs, and is working towards this change with small incremental updates.
> Remove deploy via provider

- manifests/apache.pp
- manifests/foreman_proxy.pp
- spec/acceptance/apache_spec.rb
- spec/acceptance/foreman_proxy_spec.rb
There is a pattern here between Apache and Foreman Proxy certificates, and I do think this warrants further re-factoring to simplify and unify the certificate generation and separate it from deployment. That work is more than should be undertaken to fix this bug I introduced.
> Ensure hostname directory exists when copying server cert

- manifests/candlepin.pp
- spec/acceptance/candlepin_spec.rb
Change to storing the password files in `/etc/candlepin/certs` co-located with the trustore and keystore themselves rather than storing them arbitrarily in their current location. This helps bring the Candlepin SSL configuration together.
> Move keystore and trustore password files

- manifests/ca.pp
- spec/acceptance/certs_spec.rb
- spec/acceptance/foreman_proxy_content_spec.rb
Alternative to https://github.com/theforeman/puppet-certs/pull/461. This does include the tests from 461, but not the re-factorings. I wanted to have as crisp of a solution to the regression as possible. The re-factoring, which I like, we can layer on top of the fix afterward.
If you rewind to https://github.com/theforeman/puppet-certs/commit/433dadc5ec41c2477fc6a04e056ca061fd818980, prior to this change, the `ca` resource was used to perform the copying to the server CA in the build root. This resource had the `generate` parameter built into it. This is what prevented the current regression from happening in the old design.  When deploying a foreman-proxy-content scenario in the installer, we are supplying all the certificates in the tarball. Therefore no generation needs to occur. Which …
> Fixes #37817: Only copy server CA in build root if generate is true

- manifests/ca.pp
The resource always defined the same file, just with a different source. That source is either the provided `server_ca_cert` or the default CA.
It also introduces `$default_ca_path` to make it easier to see the same value is used in multiple places.
> Merge if/else branch into a single resource declaration & introduce $default_ca_path

- lib/puppet_x/certs/provider/keystore.rb
- spec/acceptance/candlepin_spec.rb
- spec/acceptance/keystore_spec.rb
- spec/acceptance/truststore_spec.rb
This is to the 18.0-stable branch which is used in Foreman 3.11.
(cherry picked from commit dc0f12e0e2737953780f40b857fe5920e18feb5c)
> Fixes #38010 - Include keyalg in keytool for OpenJDK 17

- manifests/ca.pp
This file has been unused for a long time and removal simplifies the module.
> Ensure KATELLO-TRUSTED-SSL-CERT is absent

- lib/puppet_x/certs/provider/keystore.rb
- spec/acceptance/keystore_spec.rb
If a keystore is attempted to be generated without the `-keyalg` (see https://github.com/theforeman/puppet-certs/commit/dc0f12e0e2737953780f40b857fe5920e18feb5c) then it will create an empty keystore file. This happens in older Katello releases that do not have this change backported. This adjusts the keystore handling to regenerate the keystore if it is found to be empty.
> Regenerate keystore if the keystore is empty

- manifests/ca.pp
- manifests/init.pp
This only exists in the build directory and these references are unused.
> Drop references to the deployed CA key that is not deployed

- manifests/foreman_proxy_content.pp
This class is intended to generate certificates and the wrap them in a tarball for distribution and not to ever deploy. This has always been used in context of foreman-installer where it relies upon this being set at the top level class level (https://github.com/theforeman/foreman-installer/blob/develop/katello_certs/config/foreman-proxy-certs-answers.yaml#L4) creating a dependency that can be loosened.
> Explicitly set deploy to false for foreman_proxy_content class

- manifests/ca.pp
Refs 33130e2aa712657c746210f5419026c00ffb1cc2
Additional cleanup of files that were marked absent in a previous release and should be deployed by now.
> Remove cleanup of KATELLO-TRUSTED-SSL-CERT

- manifests/ca.pp
- spec/acceptance/certs_tar_extract_spec.rb
This was, for example, causing a password file to get created on proxies that was not used by anything.
> Only create password file when generate is true

- spec/support/acceptance/ca_bundle.rb
By using a single `=` the value is assigned, which is always true.
Fixes: 340c8ee5d9ba36d4b0bd4ddd1b9a629d3eed6256 ("Generate a ca-bundle of the default and server certificates")
> Fix assertion to do actual comparison
